"""Initial migration

Revision ID: 436db40e03ff
Revises: 
Create Date: 2024-01-11 21:13:48.186503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436db40e03ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
